# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: "Build in JDK 17"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: 17

      - name: Build with Maven - super-parent
        run: mvn -B -U -e install --file "super-parent/pom.xml"

      - name: Build with Maven - version-management-bouncy-castle
        run: mvn -B -U -e install --file "version-management-bouncy-castle/pom.xml"

      - name: Build with Maven - version-management-groovy
        run: mvn -B -U -e install --file "version-management-groovy/pom.xml"

      - name: Build with Maven - version-management-tomcat
        run: mvn -B -U -e install --file "version-management-tomcat/pom.xml"

      - name: Build with Maven - parent
        run: mvn -B -U -e install --file "parent/pom.xml"

      - name: Build with Maven - dependencies
        run: mvn -B -U -e install --file "dependencies/pom.xml"

      - name: Build with Maven - all-modules
        run: mvn -B -U -e install --file "pom.xml"
